apiVersion: skaffold/v4beta7
kind: Config
build:
  tagPolicy:
    customTemplate:
      template: "latest"
  local:
    push: true
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: quantumteknologi/ip7eomrs-4592-development
    context: .
    docker:
      dockerfile: Dockerfile.dev
      cliFlags:
        - "--cache-from=quantumteknologi/ip7eomrs-4592-development:latest"
        - "--build-arg=BUILDKIT_INLINE_CACHE=1"
    sync:
      infer:
        - 'app/**/*'
        - 'src/**/*'
        - 'public/**/*'
        - 'components/**/*'
        - '*.ts'
        - '*.js'
        - 'tsconfig.json'
        - '*.css'
        - '*.json'
        - '*.html'
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
